#pragma kernel ReadPixels

Texture2D<float4> inputTexture; // Input texture

#define MAX_ENEMY_AGENT_COUNT 512
int targetAgentCount;
float4 targetAgentUVs[MAX_ENEMY_AGENT_COUNT];

RWStructuredBuffer<float> outputBuffer; // Output buffer

[numthreads(1, 1, 1)]
void ReadPixels(uint3 id : SV_DispatchThreadID)
{
	for (int i = 0; i < targetAgentCount; ++i)
	{
		float4 color = inputTexture.Load(int3(targetAgentUVs[i].x, targetAgentUVs[i].y, 0));
		outputBuffer[i] = color.a;
	}
}